AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'config/**/*'
    - 'bin/*'
    - 'Gemfile'
    - 'db/migrate/*'
    - 'db/schema.rb'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
